# Generated by Django 4.2.6 on 2023-12-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.PositiveIntegerField()),
                ('sent_time', models.DateTimeField(auto_now=True, verbose_name='sent time')),
                ('expired_time', models.DateTimeField(auto_now=True, verbose_name='expired time')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('balance', models.FloatField(default=0.0, null=True)),
                ('account_number', models.PositiveIntegerField(default=0, null=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('curren', 'Current')], default='savings', max_length=200)),
                ('currency', models.CharField(choices=[('usd', 'Usd'), ('btc', 'Btc'), ('ngn', 'Ngn')], default='usd', max_length=200)),
                ('bank', models.CharField(choices=[('uba', 'Uba'), ('access', 'Access'), ('zineth', 'Zenith')], default='uba', max_length=200)),
                ('block', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0.0)),
                ('time_stamp', models.DateTimeField(auto_now=True, verbose_name='time stamp')),
                ('otp', models.PositiveIntegerField()),
                ('reffrence_code', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('faild', 'Faild')], max_length=200)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='App.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='App.users')),
            ],
        ),
    ]
