# Generated by Django 4.2.6 on 2024-01-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_transfer_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
